### PR TITLE
Added timezone input. Now when you click 'current' in the ngx-date-ti…

### PR DESCRIPTION
**Pull request by adammfrank**
…me popup, it will set to the correct current time, not just system time

### CODE REVIEW

**Review by nelsonGuti — COMMENTED** [review]
LGTM

**Comment by adammfrank** [comment]
> 1. Also, could we please add the feature to the changeLog file?

Is this going to be version 1.3.1 ?

**Review by nelsonGuti — APPROVED** [review]

**Comment by nelsonGuti** [comment]
> > 1. Also, could we please add the feature to the changeLog file?
> 
> Is this going to be version 1.4.0 ?

For this line on the changelog file, you can just add `UNRELEASED` and remove the date. Thanks!

**Comment by nelsonGuti** [comment]
Approved. LGTM! Just a minor comment on changelog

**Pull request merged**
